name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install lftp
        run: sudo apt-get install lftp
      
      - name: Deploy to FTP server
        run: |
          lftp -c "set ftp:ssl-allow no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }};
          mirror --reverse ./ /public_html/eco-2023"
